version: '3.7'
services:
  web:
    container_name: nginx-code-spec
    image: nginx:latest
    depends_on:
      - app
    ports:
      - 8090:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  app:
    container_name: code-spec-app
    image: code-spec-app
    env_file:
      - settings_server.env
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/docker/app.sh"]
    ports:
      - "8000:8000"
    networks:
      - default

